import { test, expect } from '@playwright/test'
import { readRecordingArtifact } from './recording-file'
import { startTrainingFromForm } from './training-flow'
import { evidencePath } from './runtime'

test('录制上下文准备期间不会漏掉第一笔交易', async ({ page }) => {
  const active = (await (await page.request.get('/api/trainings/active')).json()).training
  if (active) await page.request.post(`/api/trainings/${active.id}/abandon`)
  let release!: () => void
  const contextReady = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/trainings/*/recording-context', async route => { await contextReady; await route.continue() })
  await page.goto('/')
  await page.getByPlaceholder('搜索代码或名称，如 600519 或 贵州茅台').fill('600519')
  await page.getByRole('button', { name: /600519 贵州茅台/ }).click()
  await page.locator('input[type="date"]').fill('2026-09-01')
  await startTrainingFromForm(page)
  await expect(page.locator('.training-grid')).toHaveAttribute('inert', '')
  await page.keyboard.press('b')
  const before = await (await page.request.get('/api/trainings/active')).json()
  expect(before.trades).toHaveLength(0)
  release()
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  await expect(page.locator('.training-grid')).not.toHaveAttribute('inert', '')
  await page.getByRole('button', { name: '买入', exact: true }).click()
  await expect(page.locator('.status-message')).toContainText('成交')
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出录制', exact: true }).click()
  const download = await pending
  const output = evidencePath('first-trade-recorded.json')
  await download.saveAs(output)
  const file = await readRecordingArtifact(output)
  expect(file.gaps).toEqual([])
  expect(file.events.filter((event: any) => event.action === 'training.create').map((event: any) => event.phase)).toEqual(['started', 'finished'])
  expect(file.events.filter((event: any) => event.action === 'training.trade').map((event: any) => event.phase)).toEqual(['started', 'finished'])
})

test('默认录制交易拒单、周期和画线，暂停恢复后可导出并离线只读回放', async ({ page }) => {
  const active = (await (await page.request.get('/api/trainings/active')).json()).training
  if (active) await page.request.post(`/api/trainings/${active.id}/abandon`)
  await page.goto('/')
  await expect(page.getByLabel('记录操作', { exact: true })).toBeChecked()
  await page.getByPlaceholder('搜索代码或名称，如 600519 或 贵州茅台').fill('600519')
  await page.getByRole('button', { name: /600519 贵州茅台/ }).click()
  await page.locator('input[type="date"]').fill('2026-09-01')
  await startTrainingFromForm(page)
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  await page.getByRole('button', { name: '买入', exact: true }).click()
  await expect(page.locator('.status-message')).toContainText(/成交|买入/)
  await expect(page.getByRole('button', { name: '刷新图表', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '卖出', exact: true }).click()
  await expect(page.locator('.status-message')).toHaveClass(/error-text/)
  await page.getByRole('button', { name: '推进下一日', exact: true }).click()
  await page.getByRole('tab', { name: '周K', exact: true }).click()
  await expect(page.locator('.timeframe-tabs [aria-selected="true"]')).toHaveText('周K')
  await expect(page.getByRole('button', { name: '刷新图表', exact: true })).toBeEnabled()
  await page.getByRole('tab', { name: '月K', exact: true }).click()
  await expect(page.locator('.timeframe-tabs [aria-selected="true"]')).toHaveText('月K')
  await expect(page.getByRole('button', { name: '刷新图表', exact: true })).toBeEnabled()
  await page.getByRole('tab', { name: '日K', exact: true }).click()
  await expect(page.locator('.timeframe-tabs [aria-selected="true"]')).toHaveText('日K')
  await expect(page.getByRole('button', { name: '刷新图表', exact: true })).toBeEnabled()
  await page.locator('.draw-toolbar').getByRole('button', { name: '线段', exact: true }).click()
  const host = await page.locator('.chart-host').boundingBox()
  await page.mouse.click(host!.x + host!.width * .35, host!.y + 140)
  await page.waitForTimeout(550)
  await page.mouse.click(host!.x + host!.width * .55, host!.y + 180)
  await expect.poll(() => page.evaluate(() => (window as any).__trainerChart.drawings().length)).toBe(1)
  await expect(page.locator('.drawing-save-status')).toHaveText('已保存')
  await page.getByLabel('记录操作', { exact: true }).uncheck()
  await expect(page.getByRole('status').filter({ hasText: '已暂停记录' })).toBeVisible()
  await page.getByRole('tab', { name: '周K', exact: true }).click()
  await page.getByLabel('记录操作', { exact: true }).check()
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出录制', exact: true }).click()
  const download = await pending
  const output = evidencePath('recorded-session.json')
  await download.saveAs(output)
  const recording = await readRecordingArtifact(output)
  expect(recording.format).toBe('trainer-session')
  expect(recording.app.gitCommit).not.toBe('unknown')
  expect(recording.events.some((e: any) => e.action === 'training.trade' && e.outcome === 'accepted')).toBe(true)
  expect(recording.events.some((e: any) => e.action === 'training.trade' && e.outcome === 'rejected')).toBe(true)
  expect(recording.events.some((e: any) => e.action === 'chart.drawing.create')).toBe(true)
  expect(recording.checkpoints.some((c: any) => c.chart?.timeframe === '1M')).toBe(true)
  expect(recording.gaps.length).toBeGreaterThan(0)
  await page.getByRole('button', { name: '提前结算', exact: true }).click()
  await page.getByRole('button', { name: '完成，返回首页', exact: true }).click()
  // Replay must consume the file even if all backend endpoints are unavailable.
  await page.route('**/api/**', route => route.abort())
  await page.getByLabel('导入录制', { exact: true }).setInputFiles(output)
  await expect(page.getByRole('button', { name: '关闭回放', exact: true })).toBeVisible()
  const writes: string[] = []
  page.on('request', request => { if (/\/api\//.test(request.url()) && ['POST', 'PUT', 'DELETE'].includes(request.method())) writes.push(request.url()) })
  await page.getByRole('button', { name: '最后一步', exact: true }).click()
  await expect.poll(() => page.evaluate(() => (window as any).__trainerChart?.drawings().length ?? 0)).toBeGreaterThan(0)
  const drawingsBefore = await page.evaluate(() => (window as any).__trainerChart.drawings())
  await expect(page.getByRole('button', { name: '买入', exact: true })).toHaveCount(0)
  await page.keyboard.press('b')
  await page.keyboard.press('Delete')
  const replayHost = await page.locator('.chart-host').boundingBox()
  await page.mouse.click(replayHost!.x + 260, replayHost!.y + 150, { button: 'right' })
  expect(await page.evaluate(() => (window as any).__trainerChart.drawings())).toEqual(drawingsBefore)
  await page.screenshot({ path: evidencePath('recording-replay.png') })
  expect(writes).toEqual([])
})

test('浏览器存储恢复后可重试录制，错误不伪装成正在记录', async ({ page }) => {
  const active = (await (await page.request.get('/api/trainings/active')).json()).training
  if (active) await page.request.post(`/api/trainings/${active.id}/abandon`)
  await page.addInitScript(() => {
    const open = indexedDB.open.bind(indexedDB)
    ;(window as any).__recordingStorageFault = true
    indexedDB.open = (...args: Parameters<IDBFactory['open']>) => {
      if ((window as any).__recordingStorageFault) throw new DOMException('storage temporarily unavailable', 'UnknownError')
      return open(...args)
    }
  })
  await page.goto('/')
  await page.getByPlaceholder('搜索代码或名称，如 600519 或 贵州茅台').fill('600519')
  await page.getByRole('button', { name: /600519 贵州茅台/ }).click()
  await page.locator('input[type="date"]').fill('2026-09-01')
  await startTrainingFromForm(page)
  await expect(page.getByRole('status').filter({ hasText: '记录失败' })).toBeVisible()
  await page.evaluate(() => { (window as any).__recordingStorageFault = false })
  await page.getByRole('button', { name: '重试录制保存' }).click()
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出录制', exact: true }).click()
  const download = await pending
  const output = evidencePath('storage-recovery-session.json')
  await download.saveAs(output)
  const file = await readRecordingArtifact(output)
  expect(file.gaps.length).toBeGreaterThan(0)
  expect(file.gaps.at(-1).resumedAtSeq).not.toBeNull()
  await page.screenshot({ path: evidencePath('recording-storage-recovered.png') })
})

test('首页关闭仅影响本场，刷新保留暂停且恢复后可导出', async ({ page }) => {
  const active = (await (await page.request.get('/api/trainings/active')).json()).training
  if (active) await page.request.post(`/api/trainings/${active.id}/abandon`)
  await page.goto('/')
  await expect(page.getByLabel('记录操作', { exact: true })).toBeChecked()
  await page.getByLabel('记录操作', { exact: true }).uncheck()
  await page.getByPlaceholder('搜索代码或名称，如 600519 或 贵州茅台').fill('600519')
  await page.getByRole('button', { name: /600519 贵州茅台/ }).click()
  await page.locator('input[type="date"]').fill('2026-09-01')
  await startTrainingFromForm(page)
  await expect(page.getByRole('status').filter({ hasText: '已暂停记录' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('status').filter({ hasText: '已暂停记录' })).toBeVisible()
  await page.getByLabel('记录操作', { exact: true }).check()
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出录制', exact: true }).click()
  const download = await pending
  const output = evidencePath('initially-paused-session.json')
  await download.saveAs(output)
  const file = await readRecordingArtifact(output)
  expect(file.gaps[0].afterSeq).toBe(0)
  expect(file.gaps[0].resumedAtSeq).toBeGreaterThan(0)
  await page.getByRole('button', { name: '提前结算', exact: true }).click()
  await page.getByRole('button', { name: '完成，返回首页', exact: true }).click()
  await expect(page.getByLabel('记录操作', { exact: true })).toBeChecked()
})
